config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_for :admins, ActiveAdmin::Devise.config

  resources :sensors
  resources :notifications
  resources :home do
    get :impressum, :on=>:collection
    get :datenschutz, :on=>:collection
  end

  scope '/v1' do
    resources :api do
      get :sensors_notification_enabled, :on=>:collection
      get :sensors
    end
  end

  resources :user

  #resources :community
  #mount Thredded::Engine => '/forum'

  # below code to fix the active admin issue when table not exists in database as activeadmin tries to load every model.
  # for reference https://github.com/activeadmin/activeadmin/issues/783
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end
  root :to => 'home#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  has_many :sensor_relations, dependent: :destroy
  has_many :sensors, :through => :sensor_relations, :source => :own_sensor
  belongs_to :user
  accepts_nested_attributes_for :sensor_relations, allow_destroy: true
  validates :limit_value, numericality: true, allow_blank: true, :inclusion => 10..500
  validates :interval_to_send, presence: true
  validates :aggregation_time, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.try(:notifications)
    if @notifications.blank?
      redirect_to new_user_session_path, notice: "Erst bitte erst einloggen..."
    end
  end

  def create
    #current_user = AuthorizeApiRequest.call(request.headers).result
    sensors = OwnSensor.where(extern_db_id: params[:notification][:sensor_ids]).map { |s| s.sensor_relations.new() }
    @notification = current_user.notifications.create(
      name: params[:notification][:name], enabled: true, sensor_relations: sensors)
    respond_to do |format|
      format.html { redirect_to notifications_path }
      format.json { render json: { sensors: @notification } }
    end
  end

  def update
    @notification = current_user.notifications.where(id: params[:id]).first
    @notification.update_attributes(notification_params)
    respond_to do |format|
      format.json { respond_with_bip(@notification) }
    end
  end

  def add_sensor
    #current_user = AuthorizeApiRequest.call(request.headers).result
    sensors = OwnSensor.where(extern_db_id: params[:sensor_ids]).map { |s| s.sensor_relations.new() }
    @notification = current_user.notifications.find_or_create_by(
      sensor_relations: sensors
    )
  end

  def destroy
    puts params[:id]
    #current_user = AuthorizeApiRequest.call(request.headers).result
    current_user.notifications.where(id: params[:id]).first.destroy
    respond_to do |format|
      format.html { redirect_to notifications_path }
      format.json { }
    end
    #todo: test it
  end

  private
  def notification_params
    params.require(:notification).permit(:enabled,:name,:aggregation_time,:limit_value,:interval_to_send)
  end

end

app/views/notifications/_aggregation_time.html.erb
<span id="aggregation-time-<%= notification.id %>" class="ui dropdown green">
  <input type="hidden" name="gender">
  <i class="dropdown icon"></i>
  <div class="default text">Wähle</div>
  <div class="menu">
    <div class="item" data-value="1">eine Stunde</div>
    <div class="item" data-value="2">zwei Stunden</div>
    <div class="item" data-value="3">drei Stunden</div>
    <div class="item" data-value="4">vier Stunden</div>
    <div class="item" data-value="5">fünf Stunden</div>
    <div class="item" data-value="6">sechs Stunden</div>
    <div class="item" data-value="7">sieben Stunden</div>
    <div class="item" data-value="8">acht Stunden</div>
    <div class="item" data-value="9">neun Stunden</div>
    <div class="item" data-value="10">10 Stunden</div>
  </div>
</span>
<script type="text/javascript">
  $(document).ready(function(){
    $('#aggregation-time-<%= notification.id %>').dropdown('set selected', <%= notification.aggregation_time %>);
    $('#aggregation-time-<%= notification.id %>').dropdown({
      onChange: function() {
        var aggregation_time = $(this).dropdown('get value');
        $.ajax({
          type: 'PUT',
          dataType: 'script',
          url: "<%= notification_path(id: notification.id) %>",
            data: { notification: {
              aggregation_time: aggregation_time
            },
            authenticity_token: "<%= form_authenticity_token %>"
          }
        });
      }
    });
  })
</script>

app/views/notifications/_interval_to_send.html.erb
<span id="interval_to_send-<%= notification.id %>" class="ui dropdown green">
  <input type="hidden" name="gender">
  <i class="dropdown icon"></i>
  <div class="default text">Wähle</div>
  <div class="menu">
    <%  %>
    <div class="item" data-value="1">eine Stunde</div>
    <div class="item" data-value="2">zwei Stunden</div>
    <div class="item" data-value="3">drei Stunden</div>
    <div class="item" data-value="4">vier Stunden</div>
    <div class="item" data-value="5">fünf Stunden</div>
    <div class="item" data-value="6">sechs Stunden</div>
    <div class="item" data-value="7">sieben Stunden</div>
    <div class="item" data-value="8">acht Stunden</div>
    <div class="item" data-value="9">neun Stunden</div>
    <div class="item" data-value="10">10 Stunden</div>
  </div>
</span>
<script type="text/javascript">
  $(document).ready(function(){
    $('#interval_to_send-<%= notification.id %>').dropdown('set selected', <%= notification.interval_to_send %>);
    $('#interval_to_send-<%= notification.id %>').dropdown({
      onChange: function() {
        var interval_to_send = $(this).dropdown('get value');
        $.ajax({
          type: 'PUT',
          dataType: 'script',
          url: "<%= notification_path(id: notification.id) %>",
            data: { notification: {
              interval_to_send: interval_to_send
            },
            authenticity_token: "<%= form_authenticity_token %>"
          }
        });
      }
    });
  })
</script>

app/views/notifications/index.html.erb
<h1 class="ui center aligned header"><span><i class="mail icon"></i></span> Benachrichtigungen PM10</h1>
<div class="ui container">
  <div class="ui basic segment">

    <table class="ui compact celled definition table">
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Sensor IDs (Link auf Karte mit Linechart)</th>
          <th>Warnung bei Überschreitung des Mittelwertes über (x Stunden)</th>
          <th>Überschreitung des Mittelwertes von (µg/m³)</th>
          <th>wenn Abstand zur letzten Benachrichtigung (> x Stunden)</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

        <% @notifications.each do |n| %>
        <% n.sensors.pluck(:problem, :extern_db_id).each do |problem, extern_db_id| %>
          <% unless problem.blank? %>
            Dein Sensor mit der ID-<%= extern_db_id %> hat ein Problem (<%= problem %>)
            Weitere  <%= link_to "Informationen hier.", sensor_path(id: extern_db_id) %>
          <% end %>
        <% end %>
        <tr>
          <td class="collapsing">
            <%= best_in_place n,
                :enabled, as: :checkbox,
                collection: {
                    false: "aus",
                    true: "aktiv"}, class: 'green highlight_on_success' %>
          </td>
          <td><%= best_in_place n,
                :name, :as => :input, class: 'green highlight_on_success' %></td>
          <td>
            <% n.sensors.pluck(:problem, :extern_db_id).each do |problem, extern_db_id| %>
              <%= link_to "#{extern_db_id} #{ "(!#{problem})" unless problem.blank?}", sensor_path(id: extern_db_id) %>
            <% end %>
          </td>
          <td><%= render 'aggregation_time', notification: n %></td>
          <td><%= best_in_place n,
                :limit_value, :as => :input, class: 'green highlight_on_success', place_holder: 50 %> µg/m³</td>
          <td><%= render 'interval_to_send', notification: n %></td>
          <td><%= link_to 'löschen', notification_path(n.id), method: :delete, data: { confirm: 'Die Sensorbenachrichtigung wirklich löschen?' } %></td>
        </tr>
        <% end %>
      </tbody>
      <tfoot class="full-width">
        <tr>
          <th></th>
          <th colspan="6">
            Du kannst die Werte ändern, indem du die grünen Flächen klickst. Beachte, dass wir in der Beta Phase sind... Ändere die Werte auf eigene Verantwortung. Wir schicken eine Mail Benachrichtigung, wenn der Mittelwert der Sensoren über den gewünschten Zeitraum den Grenzwert überschreitet. Passe den Grenzwert nach deinen Wünschen an. Du kannst rechts auch einstellen, dass du nicht zu oft benachrichtigt wirst, selbst wenn es eine Überschreitung gibt... Wir empfehlen mehrere Sensoren an einem Ort für die Benachrichtigung auszuwählen. Leider kann man die Sensoren noch nicht nachträglich einer Benachrichtiung hinzufügen.
          </th>
        </tr>
      </tfoot>
    </table>
    <%= link_to 'Neuen Sensoralarm anlegen', sensors_path, class: "ui button" %>
  </div>
</div>



<script type="text/javascript">
  $(".best_in_place").best_in_place();
</script>