config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_for :admins, ActiveAdmin::Devise.config

  resources :sensors
  resources :notifications
  resources :home do
    get :impressum, :on=>:collection
    get :datenschutz, :on=>:collection
  end

  scope '/v1' do
    resources :api do
      get :sensors_notification_enabled, :on=>:collection
      get :sensors
    end
  end

  resources :user

  #resources :community
  #mount Thredded::Engine => '/forum'

  # below code to fix the active admin issue when table not exists in database as activeadmin tries to load every model.
  # for reference https://github.com/activeadmin/activeadmin/issues/783
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end
  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <!-- Required meta tags always come first -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta http-equiv="x-ua-compatible" content="ie=edge">
      <link rel="icon" href="/favicon.ico" type="image/x-icon"/>

      <title>app.luftdaten.info - dein persönlicher Sensor-Alarm</title>
      <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" integrity="sha512-07I2e+7D8p6he1SIM+1twR5TIrhUQn9+I6yjqD53JQjFiMf8EtC93ty0/5vJTZGF8aAocvHYNEDJajGdNx1IsQ==" crossorigin="" />
      <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
      <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet-src.js" integrity="sha512-WXoSHqw/t26DszhdMhOXOkI7qCiv5QWXhH9R7CgvgZMHz1ImlkVQ3uNsiQKu5wwbbxtPzFXd1hK4tzno2VqhpA==" crossorigin=""></script>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

      <%= csrf_meta_tags %>

    </head>
    <body>

      <%# Beginn Menuleiste mit App Auswahl%>
    <div class="ui attached stackable inverted menu roove" style="background-color: #16A287">
      <a class="" href="/">
        <div class="ui tiny image">
            <img src="/static/images/logo/logo-wort-bildmarke-full-trans.jpg">
          </div>
      </a>
      <% if user_signed_in? %>
        <a class="item" href="/sensors">
          <i class="map icon"></i>Sensor-Karte
        </a>
      <% else  %>
        <a class="item" href="/sensors">
          <i class="map icon"></i>Sensor-Karte
        </a>
        <%= link_to('Registrierung', new_user_registration_path, class: 'item')  %>
      <% end %>
      <% if user_signed_in? %>
        <a class="item" href="/notifications">
          <i class="list icon"></i>Meine Benachrichtigungen
        </a>
        <a class="item" href="<%= edit_user_path(current_user.id) %>">
          <i class="fa fa-user"></i>&nbsp;Profil
        </a>
      <% end %>
      <div class="right menu">
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'item') %>
        <% else %>
          <%= link_to('Login', new_user_session_path, class: 'item')  %>
        <% end %>
      </div>
    </div>

    <%# Beginn Main Content %>

    <div class="main-container">
      <div class="ui text container">
        <div id="flashes" class="column">
          <div class="ui column stackable middle aligned centered color grid">
            <% if flash[:notice] %>
              <div class="green column flash"><%= flash[:notice] %></div>
            <% end %>
            <% if flash[:alert] %>
              <div class="red column flash"><%= flash[:alert] %></div>
            <% end %>
          </div>
        </div>
      </div>
      <%= yield %>
    </div>

    <footer class="footer-distributed" style="background-color: #1ABC9C">
        <img class="ui medium image centered" src="/static/images/logo/logo-wort-bildmarke-full-trans.jpg">
    </footer>
    <footer class="footer-distributed" style="background-color: #16A287">
      <div class="ui text container">
        <div class="ui stackable inverted divided equal height stackable grid">
          <div class="three wide column">
            <h4 class="ui inverted header"></h4>
            <div class="ui inverted link list">
              <a href="<%= impressum_home_index_path%>" class="item"> Impressum</a>
              <a href="<%= datenschutz_home_index_path%>" class="item"> Datenschutz</a>
              <a href="https://github.com/luftdaten/alarm_app" class="item"> Github</a>
            </div>
          </div>
          <div class="three wide column">
            <div class="ui inverted link list">
              <p><br>
                <a href="https://github.com/luftdaten/alarm_app/issues" class="item"> Issues und Hilfe</a>
              </p>
            </div>
          </div>
          <div class="three wide column">
            <div class="ui inverted link list">
            </div>
          </div>
          <div class="six wide column">
              <div class="ui inverted link list">
                    <a href="https://codeforhamburg.org" class="item"> Code for Hamburg</a>
                    <a href="https://www.codefor.de/koeln/" class="item"> Code for Köln</a>
                    <a href="https://www.codefor.de/stuttgart/" class="item"> Code for Stuttgart</a>
                    <a href="https://github.com/luftdaten/alarm_app/issues" class="item"> Codefor.de Netzwerk</a>
                    <a href="https://okfn.de" class="item"> Open Knowledge Foundation DE e.V.</a>
                </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/forum.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <!-- Required meta tags always come first -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta http-equiv="x-ua-compatible" content="ie=edge">

      <title>Luftalarm Forum</title>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

      <%= csrf_meta_tags %>

    </head>
    <body>

      <%# Beginn Menuleiste mit App Auswahl%>
    <div class="ui attached stackable inverted menu roove">
      <div class="ui dropdown icon item">
        <i class="fa-crosshairs icon"></i>
        <div class="menu">
        </div>
      </div>
      <a class="item" href="/sensors">
        <i class="list icon"></i>Sensoren
      </a>
      <a class="item" href="/community">
        <i class="list icon"></i>Forum
      </a>


    </div>

    <%# Beginn Main Content %>

    <div class="main-container">
      <div class="ui text container">
        <div id="flashes" class="column">
          <div class="ui column stackable middle aligned centered color grid">
            <% if flash[:notice] %>
              <div class="green column flash"><%= flash[:notice] %></div>
            <% end %>
            <% if flash[:alert] %>
              <div class="red column flash"><%= flash[:alert] %></div>
            <% end %>
          </div>
        </div>
      </div>
      <%= yield %>
    </div>

  <div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header"></h4>
          <div class="ui inverted link list">
            <a href="#" class="item"></a>
          </div>
        </div>
        <div class="three wide column">
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header"></h4>
          <p></p>
        </div>
      </div>
    </div>
  </div>
</div>

    </body>
</html>